# Generated by Django 5.0.14 on 2025-04-30 00:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_conversationreply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConversationReply",
            new_name="Reply",
        ),
    ]
