# Generated by Django 5.0.14 on 2025-04-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_conversationreply_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"permissions": [("can_create_post", "Can create post")]},
        ),
    ]
